version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: ${PROJECT_NAME:-project}_app
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../docs:/app/docs
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/${PROJECT_NAME:-project}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME:-project}.rule=Host(`${PROJECT_NAME:-project}.localhost`)"
      - "traefik.http.services.${PROJECT_NAME:-project}.loadbalancer.server.port=8000"
      - "traefik.http.routers.${PROJECT_NAME:-project}.entrypoints=web"
    networks:
      - app-network
      - traefik-network

  db:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME:-project}_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${PROJECT_NAME:-project}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME:-project}_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  test-db:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME:-project}_test_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${PROJECT_NAME:-project}_test
    ports:
      - "${TEST_DB_PORT:-5433}:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  traefik-network:
    external: true
